### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kgupta26**
This should be file("...").  I was not able to generate my classes from another directory other than "src/main/protobuf". Found the solution here
https://medium.com/@mohammadabdulsami/how-to-generate-class-files-and-test-protobuf-schemas-in-scala-and-sbt-89c7728647f4

### CODE REVIEW

**Comment by thesamet** [comment]
The modification depends on what you want to accomplish. If you want the path relative to the source directory then the original example is correct.

**Comment by kgupta26** [comment]
Hi @thesamet I tried what you instructed.  And when I tried to type `protoSources` it does't recognize it.  Maybe I am missing something?

```> protoSources
[error] Not a valid command: protoSources
[error] Not a valid project ID: protoSources
[error] Expected ':'
[error] Not a valid key: protoSources (similar: protocSources, resources, watchSources)
[error] protoSources
[error]             ^
```

**Comment by kgupta26** [comment]
I also tried to use relative pathing and it didn't work :( 
```
PB.protoSources in Compile := Seq(sourceDirectory.value / "../data-dictionary")
```

but when I do this, it does. 
```
PB.protoSources in Compile := Seq(sourceDirectory.value / "../data-dictionary")
```

**Comment by thesamet** [comment]
It's `protocSources`, not `protoSources`. Also, try: `Seq(sourceDirectory.value / ".." / "data-dictionary")` - and use protocSources to see what directory is being considers. You might want to also try `(baseDirectory in LocalRootProject).value` as an alternative to `sourceDirectory.value`.

**Comment by kgupta26** [comment]
ohhh! so now I can actually see that! When I type `protocSources` in sbt console, i see that is mentions the right directory.

``` bash
> protocSources
[info] * /Users/me/Projects/streaming-platform/protocol-buffer/scala-java/src/../data-dictionary
```
Then I execute `sbt compile` to see if it now picks up my protos. It did not pick up the 2 proto that is in `../data-dictionary` :(

``` bash
> sbt compile
[info] welcome to sbt 1.4.4 (Oracle Corporation Java 1.8.0_212)
[info] loading global plugins from /Users/me/.sbt/1.0/plugins
[info] loading settings for project scala-java-build from scalapb.sbt ...
[info] loading project definition from /Users/me/Projects/streaming-platform/protocol-buffer/scala-java/project
[info] loading settings for project scala-java from build.sbt ...
[info] set current project to scala-java (in build file:/Users/me/Projects/streaming-platform/protocol-buffer/scala-java/)
[info] Executing in batch mode. For better performance use sbt's shell
[success] Total time: 0 s, completed Dec 8, 2020 2:12:08 PM
```

But when I do this in `build.sbt`
```
PB.protoSources in Compile := Seq(file("../data-dictionary"))
```

I get these outputs
```
> protocSources
[info] * ../data-dictionary
```

```
✗ sbt compile
[info] welcome to sbt 1.4.4 (Oracle Corporation Java 1.8.0_212)
[info] loading global plugins from /Users/me/.sbt/1.0/plugins
[info] loading settings for project scala-java-build from scalapb.sbt ...
[info] loading project definition from /Users/me/Projects/streaming-platform/protocol-buffer/scala-java/project
[info] loading settings for project scala-java from build.sbt ...
[info] set current project to scala-java (in build file:/Users/me/Projects/streaming-platform/protocol-buffer/scala-java/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] Compiling 2 protobuf files to /Users/me/Projects/streaming-platform/protocol-buffer/scala-java/target/scala-2.13/src_managed/main/scalapb
[info] Compiling schema /Users/me/Projects/streaming-platform/protocol-buffer/scala-java/../data-dictionary/address.proto
[info] Compiling schema /Users/me/Projects/streaming-platform/protocol-buffer/scala-java/../data-dictionary/agent.proto
[info] compiling 4 Scala sources to /Users/me/Projects/streaming-platform/protocol-buffer/scala-java/target/scala-2.13/classes ...
[success] Total time: 8 s, completed Dec 8, 2020 2:20:20 PM
```

really strange :(

**Comment by kgupta26** [comment]
```PB.protoSources in Compile := Seq((baseDirectory in LocalRootProject).value / ".." / "data-dictionary")
```
worked!

**Comment by kgupta26** [comment]
and `protocSources` looks like this 
```
> protocSources
[info] * /Users/mm10444/Projects/streaming-platform/protocol-buffer/scala-java/../data-dictionary

```

**Comment by thesamet** [comment]
Glad to know you got it to work. Let me know if you want to make any further improvements to the README.

**Comment by kgupta26** [comment]
Conclusively,

Command 1:

```
PB.protoSources in Compile := Seq((baseDirectory in LocalRootProject).value / ".." / "data-dictionary")
```

Command 2:
```
PB.protoSources in Compile := Seq(sourceDirectory.value / ".." / "data-dictionary")
```

Command 3:
```
PB.protoSources in Compile := Seq(sourceDirectory.value / "../data-dictionary")
```

All three commands yield the same output for `protocSources` in `sbt` shell

```
> protocSources
[info] * /Users/me/Projects/streaming-platform/protocol-buffer/scala-java/src/../data-dictionary
```

However, `sbt compile` only picked up my proto files for Command 1 only. Command 2 and Command 3 it did not pick them up.  I don't know what it is, but I think `(baseDirectory in LocalRootProject).value` does _something else_ compared to other two command (well at least in my case).  I'll create a small PR to reflect this in the readme.

Thanks for the help @thesamet

**Comment by thesamet** [comment]
I'd consider it a bug if these commands generate the same value for a setting, but result in different behavior. Would you be able to create a minimal project that demonstrates this?

**Comment by kgupta26** [comment]
@thesamet ahh you right.  I messed up.  I am not good with paths 😅 

it needs to be this actually (../**../**) two of them
```
PB.protoSources in Compile := Seq(sourceDirectory.value / "../../data-dictionary")
```

This command seems to be it from the root of the project. While above gets it from `src` folder (ha!)
```
PB.protoSources in Compile := Seq((baseDirectory in LocalRootProject).value / ".." / "data-dictionary")
```

No change needed.

**Pull request closed without merging**
