### PR TITLE
fix "Runtime references to undefined settings" error

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Comment by thesamet** [comment]
Can you add a failing unit test? I want to make sure there are no regressions in the future for issues like this.

**Comment by xuwei-k** [comment]
First commit is a failing test case

- https://github.com/thesamet/sbt-protoc/pull/58/commits/3804d89e6faa139b658b5cdfdc5baee32a38de66
- https://travis-ci.org/thesamet/sbt-protoc/builds/344951645#L2067-L2077

```
[info] [error] Runtime references to undefined settings: 
[info] [error] 
[info] [error]   x/compile:protocIncludePaths from y/compile:protocDependentProjectsIncludePaths ((sbtprotoc.ProtocPlugin) ProtocPlugin.scala:96)
[info] [error] 
[info] [error]   x/compile:protocSources from y/compile:protocDependentProjectsIncludePaths ((sbtprotoc.ProtocPlugin) ProtocPlugin.scala:96)
[info] [error]  
[info] [error] Use 'last' for the full log.
[info] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
[error] x sbt-protoc / disable
[error]    {line 1}  Command failed: Remote sbt initialization failed
Running sbt-protoc / scala
```

**Comment by thesamet** [comment]
@xuwei-k thanks for adding a test.

**Comment by ngbinh** [comment]
Please consider releasing a new version with this fix. Thanks

**Comment by thesamet** [comment]
Pushed 0.99.17

**Pull request merged**
