### PR TITLE
Use hashing instead of other algorithms to guarantee scala classes re…

### PR DESCRIPTION
**Pull request by michey**
…build.
Fix for https://github.com/thesamet/sbt-protoc/issues/307

### CODE REVIEW

**Comment by thesamet** [comment]
Thanks for sending the PR. Since getting the hash is more expensive, I am wondering why the "last modified" approach fails here? Do the files in the two branches have the exact same last modified time?

**Comment by michey** [comment]
Hi. It is a little bit hard for me to debug why this happens.
I've attached reproduction case and repo with the smallest possible example to this issue:
https://github.com/thesamet/sbt-protoc/issues/307

**Comment by michey** [comment]
This behavior related to [this](https://github.com/sbt/sbt/issues/6270) enhancement in sbt. Since our build pipelines do not really need this sbt feature I can close this PR for now. I'll also write a comment in [the issue](https://github.com/thesamet/sbt-protoc/issues/307) to describe proper workaround.

**Comment by thesamet** [comment]
Thanks for reporting, investigating and documentation the workaround!

**Comment by bjaglin** [comment]
I don't have time to test nor to write a scripted test, but I believe this should address the issue with no overhead ([actually it would save some FS calls](https://github.com/sbt/io/blob/162521a265b7e0ee764fb75eb5e552ec4b5f3f6c/io/src/main/scala/sbt/io/IO.scala#L420)).
https://github.com/thesamet/sbt-protoc/blob/000df10752a662a7d85127642d8c2384b912c5bc/src/main/scala/sbtprotoc/ProtocPlugin.scala#L491
```diff
-val set = IO.unzip(dep, extractTarget, "*.proto")
+val set = IO.unzip(dep, extractTarget, "*.proto", preserveLastModified = false)
```

**Pull request closed without merging**
