### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Comment by ngbinh** [comment]
@thesamet can you please consider merging this and release a new version? I can't upgrade to `0.6.0-pre2` because of this.

**Comment by thesamet** [comment]
released as 0.99.8

**Comment by ngbinh** [comment]
thanks!

**Comment by ngbinh** [comment]
@thesamet right after updating, I am seeing this error when compiling generated scala from an `OneOf` protobuf message:

```scala
object creation impossible, since method value in trait GeneratedOneof of type => Any is not defined
```

Does that ring any bell to you?

**Comment by thesamet** [comment]
Looks like we have some code generated with the previous version of ScalaPB. Can you try running `clean` in sbt prior to the build?

**Comment by ngbinh** [comment]
right, that's exactly what happened. Thanks

**Pull request merged**
