### PR TITLE
ensure Compile protos are available for import in Test

### PR DESCRIPTION
**Pull request by bjaglin**
fix regression from c785478

### CODE REVIEW

**Comment by thesamet** [comment]
Thanks for catching this! The reason I picked `includeRoot=false` is that with it, we end up adding `protoSources` twice to the include path. This also happened in the original implementation, prior to c785478. I think it would actually be better to generate settings for the Test config by default, the same way we do for the compile config, so `inConfig(Test)(sbtprotoc.ProtocPlugin.protobufConfigSettings)` wouldn't be necessary any more (which was a ptifall for some users). For those who already have this line in the and update to 0.99.31, things would continue to work, unless they have test protos that depend on compile protos.

**Comment by bjaglin** [comment]
It makes sense to go into that direction.

One note about the implementation though. Based on my experience with https://github.com/akka/akka-grpc/pull/702/commits/c5c3162545b3b6b4b33579bf76729a7b69ab78fd and going back to https://github.com/thesamet/sbt-protoc/issues/108
> For PB.protocOptions, PB.protoSources & PB.includePaths that #16 also touched, one can argue that inheriting values for these keys makes sense since they do not define target/output paths.

I think letting `includePaths` inherit from its parent(s) config(s) via scope delegation would make it easier for clients to inject `protobufConfigSettings` to another configuration like `IntegrationTest`. That way, they won't have to mess with `includePaths` - it's feels natural that a config allows children configs to link against its own artifacts.

```diff
   override def projectSettings: Seq[Def.Setting[_]] =
-     protobufGlobalSettings ++ inConfig(Compile)(protobufConfigSettings) ++ inConfig(Test)(
-      protobufConfigSettings :+ (PB.includePaths ++= (PB.includePaths in Compile).value)
-    )
+    protobufGlobalSettings ++ Seq(Compile, Test).flatMap(inConfig(_)(protocExtensionsConfigSettings))
```

```diff
-     PB.includePaths := PB.protoSources.value,
+    PB.includePaths := PB.includePaths.?.value.getOrElse(Nil),
+    PB.includePaths ++= PB.protoSources.value,
```

**Comment by thesamet** [comment]
I made the change you suggested, and added an `itconfig` test - it doesn't seem that IntegrationTest config picks up the compile's includePath. Will you be able to take a look and help making it work?

**Comment by bjaglin** [comment]
@thesamet it looks like you were missing `configs(IntegrationTest)`. I got the scripted test to work in https://github.com/thesamet/sbt-protoc/commit/b17ca642dea4db9396e8c4b7aed324cd09ef613b. I would have expected usage of configuration unknown to a project to fail, but it looks like it works partially (scope delegation not picking up the parent Configurations...).

**Comment by bjaglin** [comment]
I had a look at the implementation, and it confirms the unfortunate behavior:

https://github.com/sbt/sbt/blob/v1.3.8/main/src/main/scala/sbt/internal/Load.scala#L200
https://github.com/sbt/sbt/blob/v1.3.8/main/src/main/scala/sbt/internal/Load.scala#L217
https://github.com/sbt/sbt/blob/v1.3.8/main/src/main/scala/sbt/internal/Load.scala#L666

**Comment by thesamet** [comment]
Great, thanks for your help on this @bjaglin . I updated the test, added docs. I also update  `PB.includePaths` to ensure that what we build has no duplicates: https://github.com/thesamet/sbt-protoc/commit/0153947b1b90cfbeb1c17948310bd2aca0eed278#diff-608890ca313eef1990a1b4bb7bb3d467R152-R157

**Comment by bjaglin** [comment]
Perfect, closing this as fixed by master on https://github.com/thesamet/sbt-protoc/commit/0153947b1b90cfbeb1c17948310bd2aca0eed278

**Comment by thesamet** [comment]
Released sbt-protoc 0.99.31 which also includes c0b747847be7f894e1ea4b0e7eb4250ca1ce549d

**Pull request closed without merging**
